---
- hosts: Ansible_Hosts
  tasks:
  - name: check if java is installed
    stat:
      path: /usr/lib/jvm
    register: java_path
  - name:
    debug:
      msg: "{{java_path}}"

  - name:  install java 8
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
    when: java_path.stat.exists == False
    become: true

  - name: Download and install ElasticSearch-7.9.3
    yum:
      name: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.3-x86_64.rpm
      state: present
    become: true

  - name: Insert multiple lines using blockinfile to elasticsearch
    blockinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      block: |
        network.host: 0.0.0.0
        http.port: 9200
        discovery.type: single-node
      backup: yes
    become: true

  - name: Modify the JVM XMS and XMX parameter
    lineinfile:
      path: /etc/elasticsearch/jvm.options
      # Line to Search/Match against
      regexp: '{{item.From}}'
      # Line to Replace with
      line: '{{item.To}}'
      state: present
    with_items:
     - { From: '-Xms1g', To: '-Xms500m'}
     - { From: '-Xmx1g', To: '-Xmx700m'}
    become: true


  - name: Start and enable ElasticSearch
    service:
     daemon_reload: yes
     name: elasticsearch
     state: started
     enabled: yes
    become: true

  - name: Add the Bootstrap Customised Password to bin/elasticsearch-keystore
    shell: printf "%s" "test123" | /usr/share/elasticsearch/bin/elasticsearch-keystore add -x "bootstrap.password"
    become: true

  - name: Insert multiple lines using blockinfile to elasticsearch
    blockinfile:
      dest: /etc/elasticsearch/elasticsearch.yml
      block: |
        network.host: 0.0.0.0
        http.port: 9200
        discovery.type: single-node
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
      backup: yes
    become: true

  - name: Start and enable ElasticSearch
    service:
     name: elasticsearch
     state: restarted
    become: true

  - name: To verify the elasticsearch is up and running and accesible using the password which we have created
    shell: curl -u elastic:test123 http://localhost:9200
    register: elastic_status

  - name: To see the status
    debug:
      msg: "{{ elastic_status }}"
